name: CI/CD Pipeline

on:
  push:
    branches:
      - main   

jobs:
  checkout:
    name: Checkout & Setup
    runs-on: self-hosted   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  build:
    name: Build & Push Image
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Tag Docker Image
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:$GIT_SHA .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:$GIT_SHA ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest

      - name: Push Docker Image
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:$GIT_SHA
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
